---
mysql_users:
  - name: studia
    pass: studia
    priv: "*.*:ALL"
    host: '%'

python_packages:
  - python3
  - python3-dev
  - python-dev
  - python-pip
  - python-mysqldb
  - libxslt1-dev
  - libxml2-dev
  - libbz2-dev
  - zlib1g-dev
  - python-virtualenv
system_packages:
  - build-essential
  - vim
  - tree
  - git
  - python-software-properties
  - antiword
  - odt2txt
pip_packages:
  - virtualenv
  - virtualenvwrapper
  - ipython
web_package:
  - nginx
  - php5-fpm
  - libzmq-dev
  - php5-zmq
